In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8433, 1000, 6096, 7346],
 [8433, 1000, 6096, 1713],
 [8433, 2947, 6096, 244],
 [6380, 6055, 7217, 6439, 493],
 [6380, 6055, 7217, 6439, 6350],
 [7622, 8433, 8298, 6096, 2632],
 [6224, 7439, 996, 6439]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8433 1000 6096 7346]
 [   0    0    0    0 8433 1000 6096 1713]
 [   0    0    0    0 8433 2947 6096  244]
 [   0    0    0 6380 6055 7217 6439  493]
 [   0    0    0 6380 6055 7217 6439 6350]
 [   0    0    0 7622 8433 8298 6096 2632]
 [   0    0    0    0 6224 7439  996 6439]]


In [11]:
## feature representation
dim=10

In [13]:
print(dim,
voc_size,
sent_length)

10 10000 8


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\Utkarsh Mishra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step


array([[[-2.17866190e-02,  1.36627890e-02,  2.71036476e-03,
          3.90125997e-02, -8.74743611e-03, -4.08374183e-02,
          2.18775608e-02,  7.88521022e-04, -2.41328031e-04,
          4.95541953e-02],
        [-2.17866190e-02,  1.36627890e-02,  2.71036476e-03,
          3.90125997e-02, -8.74743611e-03, -4.08374183e-02,
          2.18775608e-02,  7.88521022e-04, -2.41328031e-04,
          4.95541953e-02],
        [-2.17866190e-02,  1.36627890e-02,  2.71036476e-03,
          3.90125997e-02, -8.74743611e-03, -4.08374183e-02,
          2.18775608e-02,  7.88521022e-04, -2.41328031e-04,
          4.95541953e-02],
        [-2.17866190e-02,  1.36627890e-02,  2.71036476e-03,
          3.90125997e-02, -8.74743611e-03, -4.08374183e-02,
          2.18775608e-02,  7.88521022e-04, -2.41328031e-04,
          4.95541953e-02],
        [ 3.06035206e-03, -8.18144158e-03,  2.44657062e-02,
          2.95682997e-03, -1.21810548e-02, -2.01270115e-02,
         -4.11350019e-02, -2.36146934e-02,  1.178818

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 8433, 1000, 6096, 7346])